unstable_features = true
edition = "2021"
version = "Two"

fn_single_line = true
format_macro_matchers = true
format_strings = true
imports_indent = "Block"
match_block_trailing_comma = true
newline_style = "Unix"
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
wrap_comments = true
group_imports = "StdExternalCrate"