[package]
name = "brc-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
brc-core = { path = "../brc-core"}
hashbrown = "0.15.4"
rustc-hash = "2.1.1"
rand = "0.9.1"
#snmalloc-rs = "0.3.6"