[package]
name = "brc-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memchr = "2.7.1"
rustc-hash = "1.1.0"
hashbrown = "0.14.5"


[dev-dependencies]
criterion = "0.5"


[[bench]]
name = "benchmarks"
harness = false
