[build]
rustflags = "-C target-cpu=native"

#[target.'cfg(windows)']
#rustflags = "-C target-cpu=native -C link-args=/STACK:5000000"
#
#[target.'cfg(target_os = "linux")']
#rustflags = "-C target-cpu=native -C link-args=-Wl,-zstack-size=5000000"